<?php $this->renderView('menus/_admin_page');?>
<div class="container">
    <div class="page-header">
        <h3 class="h3 py-3"><?= $this->getPageTitle() ?></h3>
    </div>

    <form action="/admin/store/author" method="post" accept-charset="utf-8">
        <div class="row">
            <div class="col-lg-9 col-offset-2">
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" name="name" class="form-control" required>
                </div>

                <div class="form-group mt-3">
                    <label for="email">E-mail</label>
                    <input type="text" name="email" class="form-control" required>
                </div>

                <div class="form-group mt-3">
                    <label for="nickname">Nickname</label>
                    <input type="text" name="nickname" class="form-control" required>
                </div>

                <div class="form-group mt-3">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" required>
                </div>
                <div class="form-group my-3">
                    <a href="/admin" class="btn btn-danger">Cancelar</a>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>