<header>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <div class="container">
                <img src="/assets/img/logo_coremvc.svg" class="img-logo">
                <a class="navbar-brand" href="/"><?= $this->getSiteName() ?></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse ml-auto" id="navbarResponsive">
                    <ul class="navbar-nav nav-index">
                        <li class="nav-item pl-5">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item pl-5">
                            <a class="nav-link" href="/articles">Blog</a>
                        </li>
                        <li class="nav-item pl-5">
                            <a class="nav-link" href="/about">Sobre</a>
                        </li>
                        <li class="nav-item pl-5">
                            <a class="nav-link" href="/contact">Contato</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>