<?php $this->renderView('menus/_site'); ?>
<div class="container">
    <div class="row">
        <div class="col-lg-12 my-3">
            <iframe class="w-100 map" src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d28842.89549039398!2d-51.483373293770356!3d-25.359183566524433!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbr!4v1619303470044!5m2!1sen!2sbr" allowfullscreen=""></iframe>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-lg-8 mb-4 text-center">
            <h3>Envie sua mensagem</h3>
            <p>Dúvidas, sugestões, elogios, não se acanhe! Use o formulário abaixo para enviar sua mensagem.</p>
            <p>Assim que possível, respondemos!</p>
            <!-- <form action="/send" id="contactForm" method="post"> -->
            <form target="_blank" action="https://formsubmit.co/82a2e70885bf70e8032aa1c0a1054e6c" method="POST">
            <!-- <div class="form-group">
                    <div class="form-row">
                        <div class="col">
                            <input type="text" name="name" class="form-control" placeholder="Full Name" required>
                        </div>
                        <div class="col">
                            <input type="email" name="email" class="form-control" placeholder="Email Address" required>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <textarea placeholder="Your Message" class="form-control" name="message" rows="10" required></textarea>
                </div>
                <button type="submit" class="btn btn-lg btn-dark btn-block">Submit Form</button>
            </form> -->


           
                <?php
               /* $this->renderView('alerts/_errors');
                $this->renderView('alerts/_success');*/
                ?>
                <div class="form-floating mb-2">
                    <input type="text" class="form-control" id="contactName" name="name" placeholder="John Smith">
                    <label for="floatingInput">Nome*</label>
                </div>
                <div class="row">
                    <div class="form-floating col-7 mb-2">
                        <input type="email" class="form-control" id="conatactEmail" name="email" placeholder="name@example.com">
                        <label for="floatingInput">&nbsp&nbsp&nbspEmail*</label>
                    </div>
                    <div class="form-floating col-5 mb-2">
                        <input type="text" class="form-control phone" id="contactPhone" name="phone" onkeyup="maskPhone()" maxlength="15">
                        <label for="floatingPhone">&nbsp&nbsp&nbspTelefone [Não é obrigatório]</label>
                    </div>
                </div>

                <div class="form-floating mb-2">
                    <textarea class="form-control" placeholder="Leave a comment here" id="contactMessage" name="message" style="height: 140px"></textarea>
                    <label for="floatingTextarea2">Mensagem</label>
                </div>
                <div class="row">
                    <div class="form-floating mb-3 col-3">
                        <input type="hidden" name="hidden" value="<?= ($this->view->x + $this->view->y) ?>">
                        <input type="text" class="form-control" name="soma" placeholder="<?= $this->view->x ?> + <?= $this->view->y ?>?">
                        <label for="floatingInput text-center">&nbsp&nbsp&nbsp Calcule: <?= $this->view->x ?> + <?= $this->view->y ?>?</label>
                    </div>
                    <div class="col-9 mt-3">
                        <button type="submit" class="btn btn-primary text-center" id="sendMessageButton" name="send">Enviar mensagem</button>
                    </div>
                </div>
            </form>
            -->
        </div>
    </div>
</div>