<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $this->getPageTitle('|') . $this->getSiteName() ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="nofollow, noindex" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/custom_web.css">
    <link rel="shortcut icon" href="/assets/img/favicon.png" />
    <?php if ($this->getSiteAlias() == "articles") : ?>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
        <?php require_once "../storage/marketing/google_analitcs.inc" ?>
        <?php require_once "../storage/marketing/adsense.inc" ?>
    <?php endif; ?>
</head>

<body>

    <?php $this->content(); ?>

    <!--Back totop-->
    <button type="button" class="btn btn-small btn-danger top" data-toggle="tooltip"><i class="fa fa-chevron-up"></i></button>
    <!--end totop-->

    <!-- Footer -->
    <footer class="py-4" style="background-color: #e3f2fd;"">
            <div class=" container">
        <p class="m-0 text-center text-dark">&copy; Copyright <b><?= $this->getSiteName() ?></b> - 2021<br>
            by <span id="signature">R. Soares</span></p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" async></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" async></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js" async></script>
    <script src="/assets/js/myJSfunctions.js" type="text/javascript"></script>
    <?php if ($this->getsiteAlias() == "admin") : ?>
        <script src="/assets/js/sorttable.js" type="text/javascript"></script>
        <script src="https://cdn.tiny.cloud/1/cs7lsd2xgeqwzq5cz8jhwedti34rro0c738a5svk5wtqtups/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="/assets/js/tiny5_config.js"></script>
    <?php endif; ?>
</body>
